bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'

urlpatterns = [
    path('', views.bookstore, name='bookstore'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('delete/<int:book_id>/', views.delete_book, name='delete_book'),
    path('edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('add/', views.add_book, name='add_book'),
    path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),
]

home/urls.py
from django.urls import path
from . import views
from .views import robots_txt

urlpatterns = [
    path('', views.home_view, name='home'),
    path("robots.txt", robots_txt),
]

the_book_loop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from home.views import custom_404, robots_txt

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('basket/', include('basket.urls')),
    path('customer_service/', include('customer_service.urls')),
    path('checkout/', include('checkout.urls')),
    path('user_profile/', include('user_profile.urls')),
    path("robots.txt", robots_txt),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404

home/models.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import User

# Create your models here.

class SellBook(models.Model):
    CONDITION_CHOICES = [
        ('like-new', 'Like New'),
        ('good', 'Good'),
        ('fair', 'Fair'),
    ]

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sell_book_user"
    )
    title = models.CharField(max_length=255)
    condition = models.CharField(max_length=10, choices=CONDITION_CHOICES, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    country = country = CountryField(blank_label='Country *', null=False, blank=False)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"User Book Sale: ' {self.title} ' from {self.user}"

home/forms.py
from django import forms
from .models import SellBook

class SellBookForm(forms.ModelForm):
    class Meta:
        model = SellBook
        fields = ['title', 'condition', 'message', 'price', 'country', 'town_or_city' ]

home/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse
from .forms import SellBookForm
from bookstore.models import Book
import random

# Create your views here.


def home_view(request):
    """
    Renders Home Page.
    Handles Sell book form
    Handles best seller section
    """

    form = SellBookForm()
    if request.method == 'POST':
        form = SellBookForm(request.POST)
        if form.is_valid():
            sell_book = form.save(commit=False)
            sell_book.user = request.user
            sell_book.save()
            messages.success(request, 
                             'Your book has been successfully submitted!')
            form = SellBookForm()

    all_books = list(Book.objects.all())
    best_seller_books = random.sample(all_books, min(3, len(all_books)))

    context = {
        'form': form,
        'best_seller_books': best_seller_books,
    }

    return render(request, 'home/index.html', context)


def custom_404(request, exception):
    """
    Renders 404 page.
    """
    return render(request, '404.html', status=404)


def robots_txt(request):
    """
    Generate robots.txt
    """
    content = """User-agent: *
    Disallow: /admin/
    Disallow: /checkout/
    Disallow: /checkout_success/
    Disallow: /basket/
    Allow: /signup/
    Allow: /home/

    Sitemap: https://thebookloop-38d0e34a2881.herokuapp.com/sitemap.xml"""
    return HttpResponse(content, content_type="text/plain")

home/templates/home/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}


    <section id="banner"
        class=" d-flex d-none d-sm-block home-banner text-center">
        <h2 class="d-none">
            Section Header
        </h2>
        <div>
            <p class="h1">Welcome to The Book Loop</p>
            <p>
                your own eco-friendly book community
            </p>
        </div>
        <a class="shop-btn btn text-white" href="{% url 'bookstore:bookstore' %}">
            SHOP NOW
        </a>

    </section>

    <!-- Landing Banner Img/ Mobile-specific content -->
    <section class="home-banner d-block d-sm-none p-6">
        <h2>Welcome to The Book Loop</h2>
        <a class="shop-btn btn text-white" href="{% url 'bookstore:bookstore' %}">
            SHOP NOW
        </a>
    </section>

    <section id="about" class="container">
        <h2 class="d-none">
            Section Header
        </h2>
        <div class="row about-sec">
            <div class="col-md-8 about-img">
            </div>
            <div class="col-md-6 about-content text-center">
                <p class="h3">What we do here</p>
                <hr>
                <p>
                    Welcome to The Book Loop, your online destination for second-hand books that bring stories back to
                    life!
                    We're more than just a bookstore—we're a community dedicated to promoting sustainability and
                    reducing
                    waste. By giving pre-loved books a new home, we're helping readers connect, share, and make a
                    positive
                    impact on the planet. Explore our curated selection, join the loop, and discover how small changes
                    can
                    make a big difference!
                </p>
                <p>
                    At The Book Loop, we believe every book has a story worth telling—and not just within its pages. By
                    supporting our zero-waste mission, you're contributing to a circular economy where books are passed
                    along, loved, and reused instead of discarded. Whether you're searching for a hidden gem or passing
                    on a
                    favorite title, you're part of a movement that values community, creativity, and care for the
                    environment.
                </p>
            </div>
        </div>
    </section>

    <section id="best-seller-list" class=" best-seller-sec">

        <h2 class="p-3">- Best Seller List -</h2>
        <p>Our best selling books at the moment</p>

        <hr>
        <div class="row d-flex justify-content-center best-sellers">
            {% if best_seller_books %}
            {% for book in best_seller_books %}
            <div class="col-12 col-lg-3 text-center">
                <a href="{% url 'bookstore:book_detail' book.id %}">
                    <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="best-seller-img rounded-circle">
                </a>
                <p class="mt-3">
                    <a href="{% url 'bookstore:book_detail' book.id %}" class="text-decoration-none">
                        {{ book.title }}
                        <br>
                        by {{ book.author }}
                        <br>
                        {{ book.rating }} <i class="fa-solid fa-star"></i>
                    </a>
                </p>
            </div>
            {% endfor %}
            {% else %}
            <p>No best sellers available at the moment. Check back later!</p>
            {% endif %}
        </div>
    </section>

    <section id="sell-books-form"
        class="sell-books-sec text-center text-white d-flex justify-content-center align-items-center">
        <h2 class="d-none">
            Section Header
        </h2>
        <div class="used-books-form text-center">
            <h2>We will buy your pre-loved books!</h2>
            <p class="p-3">Here at The Book Loop, we try our best to foster a high standard for zero waste.
                We would love to hear about what books you have at home and give you an amazing price!
            </p>

            {% if user.is_authenticated %}
            <form method="POST">
                <h3>Sell Your Book</h3>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.title.label_tag }}
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.condition.label_tag }}
                    {{ form.condition }}
                </div>
                <div class="form-group country-field">
                    {{ form.country.label_tag }}
                    {{ form.country }}
                </div>
                <div class="form-group">
                    {{ form.town_or_city.label_tag }}
                    {{ form.town_or_city }}
                </div>
                <div class="form-group">
                    {{ form.message.label_tag }}
                    {{ form.message }}
                </div>
                <button type="submit" class="btn btn-primary mt-3">Submit Form</button>
            </form>
            {% else %}
            <p><a href="{% url 'account_login' %}" class="text-white">Log in</a> to sell your old books today</p>
            {% endif %}
        </div>
    </section>



{% endblock %}