bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'

urlpatterns = [
    path('', views.bookstore, name='bookstore'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('delete/<int:book_id>/', views.delete_book, name='delete_book'),
    path('edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('add/', views.add_book, name='add_book'),
    path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),
]

home/urls.py
from django.urls import path
from . import views
from .views import robots_txt

urlpatterns = [
    path('', views.home_view, name='home'),
    path("robots.txt", robots_txt),
]

the_book_loop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from home.views import custom_404, robots_txt

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('basket/', include('basket.urls')),
    path('customer_service/', include('customer_service.urls')),
    path('checkout/', include('checkout.urls')),
    path('user_profile/', include('user_profile.urls')),
    path("robots.txt", robots_txt),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404

bookstore/models.py
from cloudinary.models import CloudinaryField
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Book(models.Model):
    CONDITION_CHOICES = [
        ('like-new', 'Like New'),
        ('good', 'Good'),
        ('fair', 'Fair'),
    ]

    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, null=True, blank=True)
    date_published = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    condition = models.CharField(
        max_length=10, choices=CONDITION_CHOICES, null=True, blank=True)
    rating = models.DecimalField(
        max_digits=2, decimal_places=1, null=True, blank=True)
    price = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    cover_image = CloudinaryField('image', default='placeholder')
    stock = models.PositiveIntegerField(default=0)
    in_stock = models.BooleanField(default=False, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def save(self, *args, **kwargs):
        self.in_stock = self.stock > 0
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Review(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reviewer"
    )
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name="book_reviewed"
    )
    review = models.TextField()
    rating = models.DecimalField(
        max_digits=2, decimal_places=1, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Review: ' {self.review} ' by {self.author}"

bookstore/forms.py
from django import forms
from .models import Review, Book

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review', 'rating']
        widgets = {
            'rating': forms.NumberInput(attrs={
                'type': 'range',
                'min': '1',
                'max': '5',
                'step': '0.5',
                'class': 'form-range',
                'id': 'rating-slider',
            }),
        }


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'date_published', 'description', 'condition', 'rating', 'price', 'cover_image', 'stock']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'date_published': forms.DateInput(attrs={'type': 'date'}),
            'description': forms.Textarea(attrs={'rows': 5}),
            'condition': forms.Select(attrs={'class': 'form-control'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control'}),
        }

bookstore/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.urls import reverse
from .models import Book, Review
from .forms import ReviewForm, BookForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden


# Create your views here.


def bookstore(request):
    """
    Render Bookstore page.
    Paginates Book list.
    Search bar functionality.
    """

    books = Book.objects.all().order_by('-created_at')
    query = None

    if 'q' in request.GET:
        query = request.GET['q']
        if not query:
            messages.error(request, "You didn't enter any search criteria!")
            return redirect(reverse('bookstore:bookstore'))

        queries = Q(title__icontains=query) | Q(description__icontains=query)
        books = books.filter(queries)

    paginator = Paginator(books, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'books': books,
        'search_term': query,
        'page_obj': page_obj,
    }

    return render(request, 'bookstore/bookstore.html', context)


def book_detail(request, book_id):
    """
    Renders Book Detail page.
    Renders book reviews.
    Add review functionality.
    """

    book = get_object_or_404(Book, pk=book_id)
    reviews = Review.objects.filter(book=book)
    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.book = book
            review.save()
            messages.success(request, "Your review has been submitted.")
            return redirect('bookstore:book_detail', book_id=book_id)

    context = {
        'book': book,
        'reviews': reviews,
        'form': form,
    }

    return render(request, 'bookstore/book_detail.html', context)


@login_required
def delete_book(request, book_id):
    """
    Delete a book from the store
    """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    messages.success(request, 'Book deleted!')
    return redirect(reverse('bookstore:bookstore'))


@login_required
def edit_book(request, book_id):
    """
    Edit a book details in the store
    """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated book!')
            return redirect(reverse('bookstore:book_detail', args=[book.id]))
        else:
            messages.error(
                request,
                'Failed to update book. Please ensure the form is valid.')

    else:
        form = BookForm(instance=book)
        messages.info(request, f'You are editing {book.title}')

    template = 'bookstore/edit_book.html'
    context = {
        'form': form,
        'book': book,
    }

    return render(request, template, context)


@login_required
def add_book(request):
    """
    Add a book to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()
            messages.success(request, 'Successfully added book!')
            return redirect(reverse('bookstore:book_detail', args=[book.id]))
        else:
            messages.error(
                request,
                'Failed to add book. Please ensure the form is valid.')
    else:
        form = BookForm()

    template = 'bookstore/add_book.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def delete_review(request, review_id):
    """
    View to delete a review.
    """
    review = get_object_or_404(Review, pk=review_id)

    if review.author != request.user:
        return HttpResponseForbidden(
            "You are not allowed to delete this review.")

    review.delete()
    messages.success(request, "Your review has been deleted successfully.")
    return redirect('bookstore:book_detail', book_id=review.book.id)

bookstore/templates/bookstore/add_book.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid" id="add-book">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <div class="form-wrapper py-4 px-4">
                <h2 class="logo-font text-center mb-4">Book Management</h2>
                <h5 class="text-muted text-center mb-4">Add a New Book</h5>
                <form method="POST" action="{% url 'bookstore:add_book' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'cover_image' %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% else %}
                        <!-- Custom block for the cover image -->
                        <div class="form-group">
                            <label for="{{ form.cover_image.id_for_label }}">{{ form.cover_image.label }}</label>
                            {{ form.cover_image }}
                        </div>
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-dark rounded-0" href="{% url 'bookstore:bookstore' %}">Cancel</a>
                        <button class="btn btn-dark rounded-0" type="submit">Add Book</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookstore/templates/bookstore/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Bookstore{% endblock %}

{% block content %}

<a href="{% url 'bookstore:bookstore' %}" class="p-3 text-black back-btn">
	<i class="fa-solid fa-arrow-left"></i> back to bookstore
</a>

<section id="book-detail">
	<div class="container mt-5 mb-5">
		<div class="row">
			<div class="col-md-4 p-4">
				<img src="{{ book.cover_image.url }}" alt="{{ book.title }} cover image"
					class="img-fluid book-detail-img">
			</div>
			<div class="col-md-6">
				<h2>{{ book.title }}</h2>
				<p><strong>Author:</strong> {{ book.author }}</p>
				<p><strong>Description:</strong> {{ book.description }}</p>
				<p><strong>Rating:</strong> {{ book.rating }} <i class="fa-solid fa-star"></i> </p>
				<p><strong>Published:</strong> {{ book.date_published }}</p>
				<p><strong>Condition:</strong> {{ book.condition }}</p>
				<p><strong>Price:</strong> ${{ book.price }}</p>

				<div class="d-flex">
					{% if book.in_stock %}
					<a class="btn btn-primary add-basket" href="{% url 'add_to_basket' book.id %}">
						Add to Basket
						<i class="fa-solid fa-basket-shopping"></i>
					</a>
					{% if user.is_authenticated %}
					<form action="{% url 'add_to_wishlist' %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="book_id" value="{{ book.id }}">
						<button type="submit" class="btn btn-outline-secondary add-wishlist">
							Add to Wish-List <i class="fa-solid fa-gift"></i> 
						</button>
					</form>
					{% endif %}

					{% else %}
					<button class="btn btn-secondary" disabled>
						Out of Stock
					</button>
					{% endif %}
				</div>
				<!-- Product Admin links displayed ONLY to superusers -->
				{% if request.user.is_superuser %}
				<div class="mt-5">
					<h4>
						<strong>Product Admin:</strong>
					</h4>
					<a class=" btn btn-primary edit-item" href="{% url 'bookstore:edit_book' book.id %}">Edit Item</a>
					<button class="btn btn-danger red-btn" id="deleteButton" data-book-title="{{ book.title }}"
						data-book-id="{{ book.id }}">Delete Item</button>
				</div>
				{% endif %}

				<!-- Modal for confirming delete -->
				<div class="modal" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
					aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal"
									aria-label="Close"></button>
							</div>
							<div class="modal-body">
								Are you sure you want to delete <span id="bookTitle"></span>?
								<br>
								This cannot be undone.
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
								<a id="confirmDelete" class="btn btn-danger" href="#">Yes</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="reviews">
	<div class="row">
		<div class="col-md-8 review-list p-5 border-end">
			<h3 class="text-center">Community Reviews</h3>
			{% if reviews %}
			<ul class="list-unstyled">
				{% for review in reviews %}
				<li class="mb-3">
					<strong>{{ review.author.username }}</strong> 
					<p class="mb-1">{{ review.review }}</p>
					<p>{{ review.rating }}/5 <i class="fa-solid fa-star"></i></p>
					<small>{{ review.created_on|date:"F j, Y" }}</small>

					{% if review.author == user %}
					<!-- Add a delete button for reviews posted by the logged-in user -->
					<form method="POST" action="{% url 'bookstore:delete_review' review.id %}" class="d-inline">
						{% csrf_token %}
						<button type="submit" class="btn btn-danger btn-sm mt-2 red-btn">Delete</button>
					</form>
					{% endif %}
					<hr>
				</li>
				{% endfor %}
			</ul>
			{% else %}
			<p class="text-center">No reviews yet. Be the first to review!</p>
			{% endif %}

		</div>
		<div class="col-md-4 add-review">
			<h4>Leave a Review</h4>
			{% if user.is_authenticated %}
			<form method="POST">
				{% csrf_token %}

				<!-- Rating section -->
				<div class="mb-3">
					<label for="rating-slider" class="form-label">Rating: 
						<span id="rating-value">3</span> / 5  <i class="fa-solid fa-star"></i>
					</label>
					{{ form.rating }}
				</div>
				<!-- Review Section -->
				<div class="mb-3">
					<label for="id_review" class="form-label">{{ form.review.label }}:</label>
					{{ form.review }}
				</div>
				<button type="submit" class="btn btn-primary mt-3 submit-review">Submit Review</button>
			</form>
			{% else %}
			<p><a href="{% url 'account_login' %}" class="btn btn-link">Log in</a> to leave a review.</p>
			{% endif %}
		</div>
	</div>
</section>

<!-- Link to JS file -->
<script src="{% static 'js/delete_book.js' %}"></script>
<script src="{% static 'js/rating-slider.js' %}"></script>

{% endblock %}

bookstore/templates/bookstore/bookstore.html
{% extends "base.html" %}
{% load static %}

{% block title %}Bookstore{% endblock %}

{% block content %}

<section class="bookstore">

    <div class="bookstore-content container">
        <h2 class="text-center  d-none">Welcome to the Bookstore</h2>

        <!-- Add Product for Super Users -->
        {% if request.user.is_superuser %}
        <section id="add-book-section">
            <h5 class="p-3">Product Admin</h5>
            <br>
            <a href="{% url 'bookstore:add_book' %}" class="add-book-btn m-3">
                <i class="fa-solid fa-plus"></i>
                 add book
            </a>
        </section>
        {% endif %}

        <!-- Search bar -->
        <section class="d-flex justify-content-center align-items-center p-5 search">
            <h2 class="d-none">
                Section Header
            </h2>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <form method="GET" action="{% url 'bookstore:bookstore' %}">
                    <div class="input-group w-100">
                        <input class="form-control search-input" type="text" name="q"
                            placeholder="Search books...">
                        <div class="input-group-append">
                            <button class="btn search-button" type="submit" aria-label="search-button">
                                <span class="icon">
                                    <i class="fas fa-search"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </section>

        <section id="book-list">
            <div class="container">
                {% if page_obj %}
                <div class="row">
                    {% for book in page_obj %}
                    <div class="col-md-4 mb-2">
                        <div class="card h-100 book-list-cover">
                            <img src="{{ book.cover_image.url }}" class="card-img-top book-list-cover"
                                alt="{{ book.title }}">
                            <div class="card-body text-center">
                                <h5 class="card-title">{{ book.title }}</h5>
                                <p class="card-text text-muted">{{ book.author }}</p>
                                <a href="{% url 'bookstore:book_detail' book.id %}" class="btn btn-primary detail-btn">Details</a>
                            </div>
                            <hr>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="no-results text-center mt-4">
                    <h3>Sorry, we found nothing!</h3>
                    <p>Try searching for a different title or author.</p>
                    <a href="{% url 'bookstore:bookstore' %}">Return to The Book Loop Bookstore</a>
                </div>
                {% endif %}

                <!-- Pagination controls -->
                <nav class="pag-controls" aria-label="Page navigation" {% if not page_obj.has_other_pages %}style="display: none;" {% endif %}>
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                        {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                        <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Next</span>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </section>
    </div>
</section>


<script src="{% static 'js/image_preview.js' %}"></script>

{% endblock %}

bookstore/templates/bookstore/bookstore_home.html
{% extends "base.html" %}

{% block title %}Bookstore{% endblock %}

{% block content %}

<h1>Welcome to the Bookstore</h1>

<section id="book-list">

    <div class="container my-5">
        <h1 class="text-center mb-4">Bookstore</h1>
        <div class="row">
            {% for book in page_obj %}
            <div class="col-md-3 mb-4">
                <div class="card h-100">
                    <img src="{{ book.cover_image.url }}" class="card-img-top" alt="{{ book.title }}">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ book.title }}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Pagination controls -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
                {% endif %}
            </ul>
        </nav>

</section>

{% endblock %}

bookstore/templates/bookstore/edit_book.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid" id="edit-book">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <div class="form-wrapper py-4 px-4">
                <h2 class="logo-font text-center mb-4">Book Management</h2>
                <h5 class="text-muted text-center mb-4">Edit a Book</h5>
                <form method="POST" action="{% url 'bookstore:edit_book' book.id %}" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-dark rounded-0" href="{% url 'bookstore:bookstore' %}">Cancel</a>
                        <button class="btn btn-dark rounded-0" type="submit">Update Book</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        document.getElementById('new-image').addEventListener('change', function() {
            const file = this.files[0];
            if (file) {
                document.getElementById('filename').textContent = `Image will be set to: ${file.name}`;
            }
        });
    </script>
{% endblock %}