customer_service/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.customer_service, name='customer_service'),
]

home/urls.py
from django.urls import path
from . import views
from .views import robots_txt

urlpatterns = [
    path('', views.home_view, name='home'),
    path("robots.txt", robots_txt),
]

the_book_loop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from home.views import custom_404, robots_txt

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('bookstore/', include('bookstore.urls', namespace='bookstore')),
    path('basket/', include('basket.urls')),
    path('customer_service/', include('customer_service.urls')),
    path('checkout/', include('checkout.urls')),
    path('user_profile/', include('user_profile.urls')),
    path("robots.txt", robots_txt),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404

customer_service/models.py
from django.db import models

# Create your models here.

class CustomerSupport(models.Model):
    full_name = models.CharField(max_length=255, null=True, blank=False)
    email = models.EmailField(max_length=255, null=True, blank=False)
    message = models.TextField(null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"Message: ' {self.message} ' by {self.full_name}"

customer_service/forms.py
from django import forms
from .models import CustomerSupport

class CustomerForm(forms.ModelForm):
    class Meta:
        model = CustomerSupport
        fields = ['full_name', 'email', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your full name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your message', 'rows': 4}),
        }

customer_service/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import CustomerForm

# Create your views here.


def customer_service(request):
    """ 
    Handle the customer support form submission.

    """

    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 
                'Your message has been successfully submitted.'
                'We will get back to you soon!')
            return redirect('bookstore:bookstore')
    else:
        form = CustomerForm()

    return render(request, 'customer_service/customer_service.html',
                 {'form': form})

customer_service/templates/customer_service/customer_service.html
{% extends "base.html" %}

{% block content %}

<div class="text-white customer-service-page">
    <h3 class="text-center">Customer Service</h3>
    <hr>
    <p class="text-center p-2 align-items-center justify-content-center">
        Welcome to The Book Loop's Customer Service! We're here to help you with any questions, concerns, or assistance you may need. 
        <br>
        Please fill out the form below, and our team will get back to you as soon as possible.
    </p>

    <form method="POST" class="customer-service-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_full_name" class="form-label">Full Name</label>
            {{ form.full_name }}
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="id_message" class="form-label">Message</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn text-white black-btn hover-black mt-3">Submit Form</button>
    </form>
    
</div>
{% endblock %}